language: node_js
node_js:
  - "stable"
cache: npm
install:
  - npm install
script:
  - npm run-script build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist/iwd-angular
  on:
    branch: master
